### ISSUE TITLE
Question on Router component

### ISSUE THREAD

**Issue by naglalakk** [thomashoneyman/purescript-halogen-realworld#20]
Hi and thank you for this fantastic project. I'm curious about this type declaration in Router.purs

```
type ChildSlot = Either7
  Unit
  Unit
  Unit
  Unit
  Unit
  Unit
  Unit
```

Is this so you have the ability to change Unit into something else for each component? or is it necessary to do it like this?  I admit I don't really get the logic behind either7

**Comment by thomashoneyman** [comment]
Hi @naglalakk! You've stumbled across one of the more irritating aspects of Halogen, but which has been made much better in the upcoming Halogen v5 release. I've written out an explanation below but be aware that this won't be relevant in the next release :)

For the time being, to manage child components, Halogen must know about a few things:

## 1. Child query types
Queries are the sorts of things components can do -- represented by their query type -- like submitting a form (`SubmitForm`) or creating a new todo (`CreateNewTodo`). Usually a component triggers these actions from user events in HTML, like listening for when the 'submit' button is clicked. 

But parent components need to know about the query types of their direct children, too, because a parent component can send a query to a child component. It doesn't make sense to send `SubmitForm` (from a form component query type) as an action to be performed by a todo component (which has a different query type full of todo-related behaviors), for example. So Halogen disallows querying a child component with anything except members of that child's query type.

When you have a parent component with a single type of child component, then the `ChildQuery` type for that parent component _is_ the `Query` type of the child component. But what do you do when you have multiple different types of child component? In that case, you need to combine all the various child query types into a single new sum type. 

That's done using `Coproduct`, which is kind of like a nested `Either` data type, but for things of kind `Type -> Type` (for example: queries in Halogen). But it's easier to just think of it as a way to create a unified child query type.

In the router component, I'm mounting several different components each with their own query types. So I'll use `Coproduct` to make a new unified type to serve as my parent component's child query. And because my new sum type will have 7 different query types inside, I'll use `Coproduct7`.

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/1074dd14dbb5dcf974bc1a6055cf8a5b453cc1e3/src/Component/Router.purs#L46-L53

## 2. Child slots
You might have fifteen copies of a child component (like fifteen typeaheads in a long form), so Halogen needs a way to distinguish among them. _Which_ of the typeaheads just changed selections? Which one should be toggled closed? This is solved with "slots"  (which can also be thought of as "keys" or "addresses" or "ids"). Every copy of a component gets its own slot address.

Any type that can be ordered can be used as a slot address. Custom types are common (`data TypeaheadSlot = Whiskeys | Cigars`), as are using a simple `Int`s as the child slot for a particular type of child component. And when you only have a single copy of a given type of child component, you may as well use a type that has only a single possible value to represent that: `Unit`.

When you have a single type of child component, then whatever slot type you choose to distinguish multiple copies of that child component _is_ the `ChildSlot` type for the parent component. But when you have multiple types of child component (which may themselves have multiple copies), we need to unify them all together into a sum type. This time we can just use the nested `Either` data type instead of `Coproduct`: slots are of kind `Type`, not `Type -> Type` as queries are.

So because I have 7 different types of components, I'll use `Either7` to create the type. And because I have only 1 copy of each component, I'll use `Unit` as the slot address:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/1074dd14dbb5dcf974bc1a6055cf8a5b453cc1e3/src/Component/Router.purs#L55-L62


## 3. Child Paths
At this point, Halogen is aware of the queries supported by all its direct children and where each component can be located. But these two pieces of information haven't been linked together yet. That's the reason for the `ChildPath` module. This module allows us to take our big unified `ChildQuery` and `ChildSlot` types and pull a particular query and slot out of it.

For example, `cp1` means "child path 1", which means "the first query type from `ChildQuery` and the first slot type from `ChildSlot`". And in our case, that would mean `Home.Query` and `Unit.` 

Halogen can use that to say "Ok, send a message compatible with `Home.Query` components to the address `Unit` for that type of component."

In action:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/1074dd14dbb5dcf974bc1a6055cf8a5b453cc1e3/src/Component/Router.purs#L94-L112

**Comment by naglalakk** [comment]
Wow, crystal clear. I get it now. I have only been using a single child component until now. Thank you so much for this detailed and fine explanation. I guess this can be closed now but I find this very valuable information.

**Comment by thomashoneyman** [comment]
Great! Glad I could help. I'll close the issue, but I'll also add a link to this issue in the relevant file. Thanks for asking a question that I'm sure other folks have as well :)
