### ISSUE TITLE
Simple routing questions?

### ISSUE THREAD

**Issue by dogwith1eye** [thomashoneyman/purescript-halogen-realworld#24]
Hi, i have a couple of simple routing questions.

I see that we handle the initial route and wrap it back up in a Maybe. The Router component then falls back to Home in the case of a Nothing. What's not clear to me though is how our initial route in the browser changes from  http://172.28.225.97:8080 to  http://172.28.225.97:8080/#/. I see our safeHref util will append the hash when navigating to another component. But how does our initial /#/ get appended to the route when we first start the app?

In a similar vein what is the best way for handling invalid routes? Are we able to navigate back to /#/ when an invalid route is entered into the browser?

thanks

**Comment by thomashoneyman** [comment]
Hi! Thanks for checking out the project; I'd love to answer these for you and can get you some information later today when I have a little time free.

**Comment by thomashoneyman** [comment]
@dogwith1eye -- Now that I've had a moment to review your questions I realize they point at a few parts of this project that could be improved. More on that in a bit!

Let's start with your first question.

When the application starts, we grab the hash and attempt to parse it into a `Route`. It may not be a valid route, so we represent that possible failure with a `Maybe Route` return type. The application is implemented _without_ an "invalid" route like `NotFound`, but as we'll see in a moment, that route should most likely be added.

As you noticed, this initial route is then provided to the router component at initialization. If there was a proper route, then the router will display it; if not, it will fall back to `Home`. But then comes the curious part: why is it that landing on the home page redirects to `/#/`? After all, the function that handles switching routes for us -- `matchesWith` -- only runs _on hash change_. Our `navigate` function (and `safeHref`) both work by setting the hash, but it's `matchesWith` that actually sends a query to the router to change the current route. Something is setting the hash and triggering `matchesWith` when the app starts up.

The answer [is here, in the component utils file](https://github.com/thomashoneyman/purescript-halogen-realworld/blob/master/src/Component/Utils.purs), where `guardSession` and `guardNoSession` are defined. Most pages in the application use these utilities as a way to ensure that a user is or is not logged in, and depending on that test may run the `logout` function and redirect them to the home page. When the home page is loaded, `guardSession` runs, there is no session, `logout` is run, and thus we land on the home page `/#/`.

This is not ideal. First, because `guardSession` is being used unnecessarily on the home page (we just want to load the current user if there is one, not run `logout` if none could be found), and second, because we really do want `/#/` to be appended to the URL if the user lands on the home page. That could be done by simply setting the hash if the user's initial route was the home page. This is room for improvement in the codebase (I welcome PRs!).

Now, your second question.

When an invalid route is entered in the browser, `matchesWith` will fail to parse it into a route, and in the current implementation it will simply be ignored. So there's no way right now to bounce the user to `/#/` if they enter an invalid route (unless they entered the site on an invalid route). However, generally you _do_ want to do something when a user enters an invalid route. You might redirect to the home page, you might display a 404 page, etc. The most typical solution is to provide a fallback route `NotFound` and if all other routes fail to parse, that's the result. Then all your navigation will work as usual, except in the case of failure to parse you'll get `NotFound`, which the router can use to either redirect or display a not found page.

Let me know if this helps!

**Comment by dogwith1eye** [comment]
Thank you very much for your detailed response @thomashoneyman. I hadn't really paid any attention to the guardSession logic and how it was logging us out of the app to land on the home page.

I was going through the guide for purescript-routing and saw that a NotFound constructor was an alternative way to handle routes that don't match. Thanks for confirming this is a a solution.

And thanks for your hard work on putting this project together. It really is an invaluable resource for anyone interested in understanding how to write a modern web application.

**Comment by thomashoneyman** [comment]
Glad you found this useful! I'm going to close this issue for now, but if I have some free time I'll consider looping back around to adjust the application to use a `NotFound` route. Let me know if I can answer any other questions you have :)
