### ISSUE TITLE
Use `FormError t` instead of FormError

### ISSUE THREAD

**Issue by zhujinxuan** [thomashoneyman/purescript-halogen-realworld#32]
Thank you very much for this awesome project!

Perhaps my suggestion is a bit over-engineering, but I feel like that it is better to define `FormError` with 

``` purs
import Type.Proxy (Proxy)
data FormError t
  = Required
  | TooShort
  | TooLong
  | Invalid (Proxy t)
```
, where `data Proxy t = Proxy` from purescript-proxy package.   Then FormError is typed with the kind of input.

Thank you again for this awesome project.  I learn a lot about purs from it.

Cheers,

**Comment by thomashoneyman** [comment]
Thanks for your suggestion @zhujinxuan — I’m sorry I took so long to get back to you!

I’m happy to discuss this change, but I’m not sure I fully understand its benefits. Answers to a few questions would help me understand them, and I’d also like to share some alternatives. For the time being, I'm not planning to change the error type -- but I'm open to changing my mind!

The first thing that comes to mind is this function:

```purs
errorToString :: FormError -> String
errorToString = case _ of
  Required -> "This field is required."
  TooShort -> "Not enough characters entered"
  TooLong -> "Too many characters entered"
  InvalidEmail -> "Invalid email address"
  InvalidUsername -> "Invalid username"
  InvalidAvatar -> "Invalid image URL"
```

With your change, there’s no `InvalidEmail`, `InvalidUsername`, etc. Instead, there’s just `Invalid (Proxy t)`. I’m assuming that `t` would be the type of the input (`String`, in this case), but I may be mistaken and it’s meant to represent the type that was supposed to result (`Email`, `Username`, or `Avatar`, in this case). How would you rewrite this function to accommodate the new proxies?

Next, I’m a little concerned about verbosity: while `Required`, `TooLong`, and `TooShort` don’t use the `t` type parameter, they still have to carry it in the type. That means some repeated information, like `field :: f (FormError String) String Username`, which I’m not sure makes up for the greater type clutter with helpful information. Does this sound like a reasonable concern?

Finally, I’d like to hear about an example way where this extra type information helps avoid unwanted code or an error. Are there places in the code base which are at risk that would be improved by the change?

---
I also have an alternative approach that could improve the error types. It’s over-engineering for this project, in my opinion, but I’ve seen it used elsewhere.

The errors could be more tightly bound to the field’s type. This seems to be along the lines of your suggestion. Right now, a username field can decide to fail with an `InvalidEmail` error, which doesn’t make sense for the field, and which will then render out a nonsensical error message for the field. It would be better if a form field only produced relevant errors.

This is possible using a variant for your error type. Rather than a form like this:

```purs
newtype Form r f = Form (r
  ( avatar :: f FormError String Avatar
  , username :: f FormError String Username
  , bio :: f Void String (Maybe String)
  ))
```

...in which all fields (except `bio`) can have any of the `FormError` values, we instead restrict which errors any form can have (the below is untested pseudocode so it might not be totally correct):

```purs
data Required = Required
data WrongLength = TooShort | TooLong
data Invalid t = Invalid

type Err errors = Variant errors

newtype Form r f = Form (r
  ( avatar :: f (Err (required :: Required)) String Avatar
  , username :: f (Err (wrongLength :: WrongLength, invalidUsername :: Invalid Username)) String Username
  , bio :: f Void String (Maybe String)
  ))
```

With this in place, we could no longer use a validator which produced an `Invalid Email` or `Required` error with our `username` field, because it only supports the `WrongLength` or `Invalid Username` errors. We could then match on just those errors:

```purs
printUsernameError 
  :: Err (invalidUsername :: Invalid Username, wrongLength :: WrongLength) 
  -> String
printUsernameError = match
  { invalidUsername: \_ -> "The username is not valid."
  , wrongLength: case _ of
      TooShort -> "The username is too short"
      TooLong -> "The username is too long"
  }
```

Or we could write an error printing function which matches on any of our errors; we’ll still never get a username field printing out the wrong thing because it can only possibly have `Required` or `WrongLength` errors.

```purs
printError 
  :: Err (required :: Required, wrongLength :: WrongLength, invalidUsername :: Invalid Username, invalidEmail :: Invalid Email) 
  -> String
printError = match
  { required: \_ -> "The field is required."
  , wrongLength: ...
  , invalidUsername: ...
  , invalidEmail: ...
  }
```

You could define a module of possible error types, and then combine them ad-hoc to match the requirements of any given field (and no more!).

It's verbose, however, and I'm not sure that the added complexity is worth it for a project like this one.

**Comment by zhujinxuan** [comment]
> I’m assuming that t would be the type of the input (String, in this case)
Sorry I did not elaborate it clearly.

`t` here shall be the type of Email for example.  

I think the code is a bit like something like this:

```
newtype FormError t
  = Required
  | TooShort
  | TooLong
  | Invalid (Proxy t)
newtype Username = Username String
newtype Avatar = Avatar String
newtype Form r f = Form (r
  ( avatar :: f (FormError Avatar) String Avatar
  , username :: f (FormError Username) String Username
  , bio :: f Void String (Maybe String)
  ))
```

`t` is the type of result rather than the type of input.  The idea is that we shall not have `InvalidAddress` in a email form.

**Comment by zhujinxuan** [comment]
>  Then FormError is typed with the kind of input

Sorry, I made a mistake here.  I should say `field` instead of `input` (I thought Email as Input and Form as output)

I think the `over-engineering` solution is a very nice one, the solution is:
1. A standard usage of type
2. A example usage of row type to combine (which is a much nicer alternative than a la carte in this simple problem)

This code as example benefits two kinds purs beginners:

1. from JS/TS world who are not familiar with type
2. from Haskell world who are not familiar with row

This approach adds some complexity, but these complexity is good for the teaching purpose of this project.

If you think you may accept a PR about this, I am happy to work on it.

**Comment by thomashoneyman** [comment]
I'd consider a PR for this, though I can't promise that I'll definitely merge it -- I'd need to think a bit on whether it places this project even further into advanced territory.

To cut down on verbosity, I'd recommend doing a few things.

First, in the `Validation` module, I'd recommend writing type synonyms for possible errors arising from validation:

```purs
type Required r = (required :: Unit | r)
type TooShort r = (tooShort :: Int | r)
```

You may also want to write helpers which just inject the error into the variant, if you find yourself using the same error variant for a few different validation functions.

```purs
import Type.Row (type (+))

required :: forall r. Variant (Required + r)
required = Variant.inj (SProxy :: SProxy "required") unit
```

Validation functions can then use those helpers (or you could inline the definition and not define a helper):

```purs
type Validation form m errors in out = Monad m => F.Validation form m (Variant errors) in out

isNonEmpty :: forall form m a r. Eq a => Monoid a => Validation form m (Required + r) a a
isNonEmpty = F.hoistFnE_ $ cond (_ /= mempty) required
```

This validation function now says "if the field is empty, then inject the `"required"` variant to whatever other errors also are supported.

Then, we could still produce a fairly compact representation of a given field's errors:

```purs
type UsernameError = (Required + ValidUsername + ...)

newtype Form r f = Form (r (username :: f UsernameError String Username))
```

And we can produce a larger "all errors" sum type for printing:

```purs
type AllErrors =
  ( Required
  + ValidUsername
  + ...
  )

printError :: AllErrors -> String
printError = Variant.match
  { required: \_ -> "Required"
  , tooShort: \n -> "Must be longer than " <> show n <> " characters."
  , ...
  }
```

---

I'd recommend organizing things such that the error types are defined with the validation functions that introduce them. So the error `Required` would be defined above the group of functions which might produce a `Required` error. Usually it's a one-to-one match, so the pattern would be "error type, error function, error type, error function."

Then, at the top of the file, you could define an `AllErrors` type and `printError` function to be used throughout the application.

Then, with each form, you can define error types for fields either inline (if they're _really_ short) or above the form definition.

---

Feel free to reach out via email or Slack (functionalprogramming.slack.com) or by responding here if there's anything else I can do to help.

**Comment by zhujinxuan** [comment]
Great!  I will work on this next weekend.

<del>Shall I try to base the PR on master? or on halogen5?</del>
Sorry, I did not notice the halogen5 is merged already.

**Comment by thomashoneyman** [comment]
I'm going to close this issue for inactivity, but feel free to continue discussing here. Thanks!
