### ISSUE TITLE
Consider using "Extended" pattern to get rid of "Util" packages

### ISSUE THREAD

**Issue by Unisay** [thomashoneyman/purescript-halogen-realworld#35]
I've noticed some modules with `Utils` suffix:
* `Conduit.Api.Utils`
* `Conduit.Component.HTML.Utils`

`Utils` is quite a broad category of things, so such modules have potential to absorb lots of unrelated functions and become a mess (esp. in large projects/teams)

One way of dealing with this problem is described by Jasper here:
https://jaspervdj.be/posts/2015-01-20-haskell-design-patterns-extended-modules.html

Wdyt?

**Comment by thomashoneyman** [comment]
I hadn’t come across the `Extended` module approach before; thank you for sharing! I spent some time thinking about this an discussed it with colleagues at Awake Security. Ultimately while I think it’s a potentially valuable way to organize a project, I would prefer to remain with `Utils` modules for now. Here are my reasons:

**PureScript IDE support**
Auto imports are a big reason why `Extended` modules are less useful in PureScript. 

First, if you add re-exports to your project (like `Halogen.HTML.Extended`) you now have more options as to where to import a function from. That proliferates in the menu of options available to auto-import and requires you to manually adjust the import if you inadvertently import from `Halogen.HTML` instead of the intended `Halogen.HTML.Extended`, and to deal with ensuring developers have the same idea of where to import things from.

Second, there’s less value in having a specific single module to go to for imports. When the IDE server is auto-suggesting functions or types to you from the correct module, you can just tab-complete the function or type. It’s then imported and your imports are sorted. That's not just true of a "blessed" editor -- Vim, Emacs, Atom, VSCode, etc. are supported by `psc-ide`.

**Re-export limitations**
Another reason `Extended` modules might be frustrating to work with in practice is that PureScript doesn’t let you re-export everything in a module without literally listing _all functions and types_ from the module you’ve put the re-export in. For example, an extended Halogen module would look like this:

```purs
module Halogen.HTML.Extended 
  ( module Halogen.HTML
  , safeHref
  ) where

import Halogen.HTML

safeHref = ...
```

Now you’ve got to manage these exports (added a new function? don’t forget to add it to the list of exports!). 

**Similarities with Utils modules**
Finally, I don’t think that utils modules are so far away from the `Extended` modules from the linked article. Utils are also given reasonable namespaces, like `Conduit.HTML.Utils`, which can help solve the problem of “Where does this go? Just shove it in a global utils module!” with something more akin to extended modules. 

They provide, for me, a middle ground that leverages the strengths of auto-imports, avoids the pitfalls of re-exports in an application, and captures most of the same benefits that the extended modules do.

I'm closing this for now, but I'm happy to hear other opinions!
