### ISSUE TITLE
Add Travis CI build?

### ISSUE THREAD

**Issue by FranklinChen** [thomashoneyman/purescript-halogen-realworld#36]
It might be a good idea to add a Travis CI build. I just did `npm install` and it failed at
```
> install-purescript --purs-ver=0.12.5
```

so something's wrong.

**Comment by thomashoneyman** [comment]
I agree, this should have a continuous integration build. I'm most familiar with Circle CI, but I'm also open to Travis. I can do this at some point soon, but if anyone else would like to submit this as PR I welcome that, too!

With regards to your failure installing PureScript, I should have updated the dependency to be `purescript: 0.13.2` and overlooked it. You're right that this could be caught by continuous integration.

In this case, I believe you're seeing a failure because [of this problem with the NPM installer for PureScript](https://discourse.purescript.org/t/security-announcement-malicious-code-in-purescript-npm-installer/854). Installing PureScript 0.13.2 should work instead.

I've updated the dependency in the master branch if you'd like to checkout again.

**Comment by thomashoneyman** [comment]
@FranklinChen I've added continuous integration via Circle CI and a badge to the README displaying the build status. Thanks for the suggestion!
