### ISSUE TITLE
Conduit.Component.RawHTML will fail with "require is not defined"  (var marked =require("marked");)

### ISSUE THREAD

**Issue by srghma** [thomashoneyman/purescript-halogen-realworld#37]
in `dist/app.js` I have 

```
})(PS["Conduit.Component.RawHTML"] = PS["Conduit.Component.RawHTML"] || {});
(function(exports) {

  var marked =require("marked");

  // Next, we'll perform any setup necessary before exporting functions. In our case, we'll turn off
  // the 'pedantic' option to be more lenient with parsing, and we'll enable GitHub-flavored
  // markdown.
  marked.setOptions({
    pedantic: false,
    gfm: true
  });
```

I didnt check, but `var marked =require("marked");` should fail

to resolve we could use `rollup-plugin-purs` and `rollup-plugin-node-resolve` (source https://github.com/purescript/purescript/issues/2621#issuecomment-277430685)

P.S. would be also cool to add https://www.npmjs.com/package/rollup-plugin-prepack

**Comment by thomashoneyman** [comment]
@srghma PureScript generates CommonJS modules, which use the `require` keyword. For that reason, the code snippet you shared should be fine.

For more information about PureScript and CommonJS, see these issues on the PureScript compiler:

* [ES modules #3613](https://github.com/purescript/purescript/issues/3613)
* [Use ES6 modules instead of CommonJS #1206](https://github.com/purescript/purescript/issues/1206)

CommonJS and ES6 modules are both fine in JavaScript; this project uses Parcel as a bundling tool which allows you to use various module types. See:

* [Webpack module imports](https://webpack.js.org/concepts/modules/)
* [Parcel module imports](https://parceljs.org/javascript.html)

I should get this project up on GitHub Pages to demonstrate, but if you build and run this project locally it opens up just fine.

> I didnt check, but `var marked =require("marked");` should fail

I'm going to close this issue, but if you run this and the code _does_ fail, then feel free to re-open it.

---

> P.S. would be also cool to add https://www.npmjs.com/package/rollup-plugin-prepack

I'm open to PR's! I'm not familiar with this project, but if it makes the generated JavaScript more efficient or bundle sizes smaller then I'm interested.
