### ISSUE TITLE
Help: Logout button in Header

### ISSUE THREAD

**Issue by Cmdv** [thomashoneyman/purescript-halogen-realworld#48]
I'm trying to add a logout button to `Conduit.Component.HTML.Header` but when looking at the current implementation in `Conduit.Page.Settings`:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/4581af1e04044a129d1c7fea15e99d75ecfbe3e2/src/Page/Settings.purs#L106

it's using it's own `handleAction` which I can't really do as I don't have access to `H.Component`:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/4581af1e04044a129d1c7fea15e99d75ecfbe3e2/src/Component/HTML/Header.purs#L20

Could the solution be that I pass this message up to the `Page.Home` component and deal with it there or convert `header` to have it's own `handleAction` etc? (which to me feels nicer as better dealing with logout in one place)

I'm just unsure how either would look like codewise and can't seem to find another place in the codebase that does what I'm after. 😃

**Comment by thomashoneyman** [comment]
If I'm understanding you correctly, you'd like to add a logout button to the header that's visible everywhere the header is rendered (if the user is logged in). In that case there are a few options:

### 1. Make the header function a component

The first option is to make the header function into its own component which connects to global state, decides what to render based on that, and implements its own logout action. Then anything rendering the header can render the component and be done with it. 

You now have to do a little more ceremony to use the header -- namely, now there has to be a slot for it managed by the parent component -- but the action is encapsulated so the parent component doesn't have to worry about how to log you out. Given that the header is present everywhere it seems like a reasonable trade-off to make.

### 2. Give the header function an action as an argument

The header already accepts a `Route` and a `Maybe { | ProfileRep }` as arguments. That way it can render conditionally on the route and tell if you're logged in. But we now need to do more: we can render a logout button if you're logged in, but we also need to actually log you out if you click it.

One way to do this is to also accept an action as an argument, and trigger it on click. It's the parent's responsibility to know how to handle that action. For instance:

```purs
header :: forall i act r. Maybe { | ProfileRep r } -> Route -> act -> HH.HTML i act
header currentUser route act =
  ...
  HH.button [ HE.onClick \_ -> Just act ] [ HH.text "Logout" ]
```

Now this is still a pure function, and the parent component is responsible for providing one of its own actions to handle the logout click. For example, if this header were rendered on the Settings page, then the Settings component would provide its `LogUserOut` action.

#### Extra fancy: make a component part

Let's say you don't want to make a new component for the header, but you also don't want to make every component re-implement the same behavior for logging out. In that case, you can leave it as a pure function which accepts an action as an argument, but you can _also_ implement an evaluation function in `HalogenM` that can be imported along with the pure function for rendering.

For instance, the "favorite" button is a pure function + a pair of helper functions that can be run in HalogenM to actually do the work:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/master/src/Component/Part/FavoriteButton.purs

The parent component has to make an action to pass to the favorite button, but it doesn't have to implement what that action _does_ when evaluated. Instead, it simply imports the relevant function in `HalogenM` from the same FavoriteButton file:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/76ec47b8c0c2436e342e72ef6aa6f051bc90a05b/src/Page/Home.purs#L137

This sort of straddles the line between a pure function and a full-blown component.

## What would I do?

The header feels like enough internal state and behavior to be a component, especially because components like `Home` appear to connect to global state only to pull the current user out and pass it down to the header (which could then do this for itself).

However, I wanted you to be aware of other options, and I'd recommend trying both ways -- perhaps first having the header accept another argument, then make it a component part, and finally just make it a full component, and see which one feels most natural in the code.

**Comment by Cmdv** [comment]
@thomashoneyman thanks so much for the very informative reply. 

I think I'm really close the only issue I'm having is how to use my component in situ, so I have:

```
data Action
  = LogUserOut

type State =
  { currentUser :: Maybe Profile
  , route :: Route
  }

type Input =
  { currentUser :: Maybe Profile
  , route :: Route
  }

component
  :: forall r m
   . MonadAff m
  => MonadAsk { userEnv :: UserEnv | r } m
  => Navigate m
  => H.Component HH.HTML (Const Void) Input Void m
component = H.mkComponent
  { initialState
  , render
  , eval: H.mkEval $ H.defaultEval { handleAction = handleAction }
  }
  where
  initialState { currentUser, route } =
    { currentUser
    , route
    }

  handleAction = case _ of
    LogUserOut -> logout

  render { currentUser, route } =
    HH.div
    [ css "main-menu menu-fixed menu-light menu-accordion menu-shadow" ]
    [ HH.div
      [ css "main-menu-content" ]
      [ HH.ul
        [ css "navigation navigation-main"
        , HP.id_ "main-menu-navigation"
        ]
        , whenElem (isJust currentUser) \_ ->
          HH.li
          []
          [ HH.a
            [ HE.onClick \_ -> Just LogUserOut ]
            [ HH.i
              [css "ft-lock"]
              []
            , HH.span
              [css "menu-title"]
              [ HH.text "Logout" ]
            ]
          ]
        ]
      ]
    ]
```

But I just can't work out how to use `HH.slot` inside one of my pages 🤔

**Comment by thomashoneyman** [comment]
You would need to give the parent component (`Home`, for example) a slot type, like is done here in the router:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/76ec47b8c0c2436e342e72ef6aa6f051bc90a05b/src/Component/Router.purs#L55-L57

For example, it might be:

```purs
type ChildSlots = ( header :: H.Slot ... )
```

Then, in your rendering code, you'd use the component, also demonstrated in the router:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/76ec47b8c0c2436e342e72ef6aa6f051bc90a05b/src/Component/Router.purs#L122-L125

For example, in the parent component's HTML:

```purs
render { currentUser, route } = 
  HH.div
    [ ... ]
    [ HH.slot (SProxy :: _ "header") unit Header.component { currentUser, route } absurd
```

where `absurd` is used if you don't care about handling output messages from the component (which you don't, because the header component has no output messages).

Also, as a brief note, you only need to have the `MonadAsk { userEnv }` constraint if you are actually pulling the user environment out of the global state. Since in your implementation of the header component yo pass the user info via `Input` you don't actually need access to the global state. 

If you _did_ want to retrieve that information from the global state instead of manually passing it down from a parent, you'd use the `connect` higher-order component as demonstrated here:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/76ec47b8c0c2436e342e72ef6aa6f051bc90a05b/src/Page/Home.purs#L77

**Comment by Cmdv** [comment]
Thanks again @thomashoneyman turns out I had slight issues with passing things into the child slot because it would actually re render before a `currentUser` would get passed so the initialiser would be set to Nothing and it would not receive the update so had to add:

```
, eval: H.mkEval $ H.defaultEval
      { handleAction = handleAction
      , receive = Just <<< Receive -- <<<<<<<
      }
```

feel free to close 👍
