### ISSUE TITLE
Show tags in editor when editing an article

### ISSUE THREAD

**Issue by mjepronk** [thomashoneyman/purescript-halogen-realworld#54]
Hi,

I'm using this project as a basis to create my own PS Halogen based app. Now I wonder how to handle the case when editing a form that represents an existing object (with initial data). My form contains various components that should have their state initialized from the form data (handled by formless).
Sadly, your code does not initialize the TagInput component when editing an existing article, as that would show exactly the code I would need :-)

Update: This is my attempt:
https://github.com/mjepronk/purescript-halogen-realworld/commit/ad0bc605d32c81eb444a0925d1c0cab75d12e866
The hardcoded tags work, but I can't get it to work with the form values (the commented part `F.getInput proxies.tagList form`).

Thanks again for all your work!

**Comment by thomashoneyman** [comment]
Hi @mjepronk, thanks for bringing this up! It's a mistake not to be initializing the tags from the form data, and so it requires a fix.

As you noticed there are two ways you might handle this and both rely on the fact that the form state is available in the parent component of the tag input.

1. You can provide tags to the `TagInput` component via input. One way is to have the `Set Tag` provided at the start and to overwrite the state each time this input is received, which is essentially saying that the state for the tag component can be managed externally if you want. Another is to have `Maybe (Set Tag)` provided as input, which allows the possibility for a parent component to opt-in to managing the state (in the `Nothing` case the tag input is self-contained, and in the `Just` case the parent has some state it manages on behalf of the tag input).

2. You can add a query, `data Query a = SetTags (Set Tags) a` to the tag input, so that a parent component can at any point overwrite the tag state. This could be used after `loadForm` at initialization to set the tag input's state and then not bother managing the input afterwards.
