### ISSUE TITLE
Another installation warning - yarn bundle

### ISSUE THREAD

**Issue by jamnut** [thomashoneyman/purescript-halogen-realworld#62]
Sorry for the noob questions, but at this point I don't know what can be safely ignored and what will cause problems down the road.

Is there something wrong with my tool setup or is this save to ignore?

I'm running the following:
yarn 1.22.4
npm 6.14.5
WSL Ubunto 18.04.4

$ yarn bundle
yarn run v1.22.4
$ npm run bundle:build && npm run bundle:dce && npm run bundle:parcel
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1589592225223-0.10801633644455455/node but npm is using /home/steve/.local/lib/node-v12.16.3-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

**Comment by thomashoneyman** [comment]
This doesn't look like an error related to installation but rather a warning that the binary being used to run the script is installed by Yarn, but the NPM tool itself defaults to a different binary. I'm not familiar with this warning myself but it looks benign.

Since this is an issue about NPM / Yarn and not this app specifically, I'm going to close it, but we can continue talking through this in the issue here -- feel free to continue asking questions!

I found folks facing the same error here:
https://github.com/npm/npm/issues/14372

Specifically this answer seems to address what you're dealing with:
https://github.com/npm/npm/issues/14372#issuecomment-274318330

**Comment by jamnut** [comment]
Thanks!

I've been using npm/spago/yarn some what blindly from the docs and discourse.  Sounds like (as usual) that is a little dangerous and I should really take the time to understand what the tools are really doing for me.
